# copy this to config.yaml befor running wolnut
log_level: INFO  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL

nut:
  ups: "ups@localhost"        # Format: <ups-name>@<host>
  username: "upsmon"          # Optional: omit if NUT server doesn't require auth
  password: "password"

poll_interval: 15             # Poll interval in seconds — should be shorter than the NUT shutdown delay on any client

wake_on:
  restore_delay_sec: 30       # Delay (in seconds) after power is restored before sending WOL
  min_battery_percent: 25     # Wait until battery reaches this percent before WOL
  client_timeout_sec: 600     # Time to wait for client to come back online before logging an error
  reattempt_delay: 30         # Minimum time (in seconds) between WOL attempts per client

clients:
  - name: "Server A"                # Human-readable name
    type: wol                     # Choose a client type, wol, idrac, ilo, sm_ipmi(supermicro)
    host: 192.168.0.100             # IP address preferred for reliability
    mac: aa:bb:cc:dd:ee:ff

  - name: "Server B"                # Human-readable name
    type: wol                     # Choose a client type, wol, idrac, ilo, sm_ipmi(supermicro)
    host: 192.168.0.101             # IP address preferred for reliability
    mac: auto                     # MAC will be resolved using ARP at runtime

  - name: Dell R740
    type: idrac
    host: server.local            # You can use a hostname if it resolves to a reachable interface
    ipmi_host: 192.168.0.10
    username: root
    password: calvin
    verify_ssl: false
  
